# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8187a67a56eda9d890b0d110435034466a0586d8688ee21829f8b1f65222b5fee28ba318735f1cbca0eb3ebcf5b29f93f6b71b79519c84a935b24b6e8b3b186d

test:
  secret_key_base: 68025dfe2c1e30d6547e6a1021c7aa6c5005112a2cffccab7a3e02dd002fe3fc699007e14ff7e4542dc39586562ec65c0d3a6c351c1fbc869630280e940119bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
